{
 "title": "Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Nginx req/min",
   "type": "graph",
   "description": "Nginx requests per minute",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "VM1's CPU Load (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=\"vm1.dystopia.net.:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"vm1.dystopia.net.:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"vm1.dystopia.net.:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "VM2's CPU (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=\"vm2.dystopia.net.:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"vm2.dystopia.net.:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"vm2.dystopia.net.:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL q/min",
   "type": "graph",
   "description": "MySQL queries per minute",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal - node_memory_MemAvailable) / (node_memory_MemTotal) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bind Status",
   "type": "stat",
   "description": "Here you can find the answer to the eternal question among sysadmins... does DNS work?",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "DNS q/min",
   "type": "graph",
   "description": "DNS queries per minute",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}