{
 "title": "Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "appname",
    "label": "Appname",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=appname"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=hostname"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=severity"
   },
   { "name": "Query", "label": "Query" }
  ]
 },
 "panels": [
  {
   "title": "Systems' status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "nginx_up", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "Nginx req/min",
     "type": "graph",
     "description": "Nginx requests per minute",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nginx_http_requests_total[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "VM1's CPU Load (%)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "%" }
     ],
     "targets": [
      {
       "expr": "(((count(count(node_cpu{instance=\"vm1:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"vm1:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"vm1:9100\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "VM2's CPU (%)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "%" }
     ],
     "targets": [
      {
       "expr": "(((count(count(node_cpu{instance=\"vm2:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"vm2:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"vm2:9100\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "MySQL Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "mysql_up" }
     ]
    },
    {
     "title": "MySQL q/min",
     "type": "graph",
     "description": "MySQL queries per minute",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mysql_global_status_queries[1m])"
      }
     ]
    },
    {
     "title": "Memory Usage (%)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "%" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal - node_memory_MemAvailable) / (node_memory_MemTotal) * 100",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Bind Status",
     "type": "stat",
     "description": "Here you can find the answer to the eternal question among sysadmins... does DNS work?",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "bind_up" }
     ]
    },
    {
     "title": "DNS q/min",
     "type": "graph",
     "description": "DNS queries per minute",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(bind_resolver_queries_total[1m])",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection latency (ms)",
     "type": "graph",
     "description": "Report of the connection latency from the 2nd VM to google.com, twitter.com and cloudflare.com",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "milliseconds" }
     ],
     "targets": [
      {
       "alias": "Target: [[tag_dst]]",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "dst" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "latency",
       "select": [
        [
         { "params": [ "rtt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Syslog messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syslog messages count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Info",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "severity_code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "severity", "operator": "=", "value": "info" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
        { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
       ]
      },
      {
       "alias": "Notice",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "severity_code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "severity", "operator": "=", "value": "notice" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
        { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
       ]
      },
      {
       "alias": "Warning",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "syslog",
       "query": "SELECT count(\"severity_code\") FROM \"syslog\" WHERE (\"severity\" = 'info' AND \"hostname\" =~ /^$hostname$/ AND \"severity\" =~ /^$severity$/ AND \"appname\" =~ /^$appname$/) AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "severity_code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "severity", "operator": "=", "value": "warning" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
        { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
       ]
      },
      {
       "alias": "Error",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "severity_code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "severity", "operator": "=", "value": "err" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
        { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
       ]
      },
      {
       "alias": "Critical",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "severity_code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "severity", "operator": "=", "value": "crit" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
        { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
       ]
      },
      {
       "alias": "Alert",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "severity_code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "severity", "operator": "=", "value": "alert" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
        { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
       ]
      },
      {
       "alias": "Emergancy",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "severity_code" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "severity", "operator": "=", "value": "emerg" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
        { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
       ]
      }
     ]
    },
    {
     "title": "Syslog messages",
     "type": "table",
     "description": "Report of syslog messages",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "appname" ], "type": "tag" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "severity_code" ], "type": "field" }
        ],
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
        { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}