---
- name: He who fails to prepare prepares to fail
  import_playbook: headstart.yaml

- name: DNS server
  hosts: dns_servers
  gather_facts: false
  become: yes
  roles:
    - bind

- name: DNS configuration
  hosts: dns_config
  gather_facts: false
  become: yes
  roles:
    - dns_config
