---
- name: Install Bind9 DNS
  apt: 
    name: bind9
    state: latest

- name: Override Bind9 configuration
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart Bind9

- name: Configure master zone
  template:
    src: db.dystopia.j2
    dest: /etc/bind/db.{{ domain_name }}
  notify: Reload rndc
  
- name: Configure {{ item }} master zone
  template:
    src: db.{{ item }}.j2
    dest: /etc/bind/db.{{ item }}
  notify: Reload rndc
  loop:
    - vm1
    - vm2
