---
- name: Install Bind9 exporter
  apt:
    name: prometheus-bind-exporter
    state: latest

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Enable and start Bind9 exporter
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes
