---
- name: Install keepalived
  apt:
    name: keepalived
    state: latest

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Download and unarchive keepalived exporter
  unarchive:
    src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.1.0/keepalived-exporter-1.1.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create keepalived exporter service
  template:
    src: keepalived-prometheus-exporter.service.j2
    dest: /etc/systemd/system/keepalived-prometheus-exporter.service
  notify: 
    - Reload systemd
    - Restart keepalived exporter

# Before starting the service - run handlers

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Check if the keepalived service is started and if it is not, start it
  service:
    name: keepalived
    state: started
    enabled: yes

- name: Check if the keepalived Prometheus exporter service is started and if it is not, start it
  service:
    name: keepalived-prometheus-exporter
    state: started
    enabled: yes
