---
- name: Install Prometheus
  apt:
    name: prometheus
    state: latest

- name: Duplicate Prometheus' service configration
  copy:
    src: /lib/systemd/system/prometheus.service
    dest: /etc/systemd/system/
    remote_src: yes

- name: Configure Prometheus' web path
  lineinfile:
    dest: /etc/systemd/system/prometheus.service
    regex: 'ExecStart='
    line: "ExecStart=/usr/bin/prometheus $ARGS --web.external-url=http://vm1.{{ domain_name }}:11480/prometheus"
    state: present
  notify: Restart Prometheus

- name: Configure Prometheus
  template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus
