---
- name: Install Docker
  apt:
    name:
      - python3-docker
      - docker.io
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

# Before starting the service - run handlers

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Check if the service is started and if it is not, start it
  service:
    name: docker
    state: started
    enabled: yes
